import type { Product } from "./types";

export const generatedProducts: Product[] = [
  {
    "id": "alitas-de-pollo",
    "name": "Alitas De Pollo",
    "slug": "alitas-de-pollo",
    "description": "Producto disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Pollos",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$3.350",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/alitas-de-pollo.png",
    "status": "available",
    "isActive": true,
    "featured": true,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "arandanos",
    "name": "Arandanos",
    "slug": "arandanos",
    "description": "Producto congelado disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Congelados",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$4.400",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/arandanos.png",
    "status": "available",
    "isActive": true,
    "featured": true,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "arrollado",
    "name": "Arrollado",
    "slug": "arrollado",
    "description": "Producto disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Cerdo",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$4.700",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/arrollado.png",
    "status": "available",
    "isActive": true,
    "featured": true,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "arvejitas",
    "name": "Arvejitas",
    "slug": "arvejitas",
    "description": "Producto congelado para negocios, cocinerias y locales de comida. Confirmar disponibilidad directamente con Hugo.",
    "category": "Papas y vegetales",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$450",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/arvejitas.png",
    "status": "available",
    "isActive": true,
    "featured": true,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "ave-marinada",
    "name": "Ave Marinada",
    "slug": "ave-marinada",
    "description": "Producto disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Pollos",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$15.000",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/ave-marinada.png",
    "status": "available",
    "isActive": true,
    "featured": true,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "carne-molida",
    "name": "Carne Molida",
    "slug": "carne-molida",
    "description": "Producto disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Vacuno",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$1.200",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/carne-molida.png",
    "status": "available",
    "isActive": true,
    "featured": true,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "chicken-fingers",
    "name": "Chicken Fingers",
    "slug": "chicken-fingers",
    "description": "Producto disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Pollos",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "Consultar",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/chicken-fingers.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "choclo-desgranado",
    "name": "Choclo Desgranado",
    "slug": "choclo-desgranado",
    "description": "Producto congelado para negocios, cocinerias y locales de comida. Confirmar disponibilidad directamente con Hugo.",
    "category": "Papas y vegetales",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$500",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/choclo-desgranado.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "choclo-trozado",
    "name": "Choclo Trozado",
    "slug": "choclo-trozado",
    "description": "Producto congelado para negocios, cocinerias y locales de comida. Confirmar disponibilidad directamente con Hugo.",
    "category": "Papas y vegetales",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$700",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/choclo-trozado.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "filete-de-reineta",
    "name": "Filete De Reineta",
    "slug": "filete-de-reineta",
    "description": "Producto disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Vacuno",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$10.000",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/filete-de-reineta.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "frutillas",
    "name": "Frutillas",
    "slug": "frutillas",
    "description": "Producto congelado disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Congelados",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$3.100",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/frutillas.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "hamburguesa",
    "name": "Hamburguesa",
    "slug": "hamburguesa",
    "description": "Producto disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Vacuno",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$900",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/hamburguesa.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "jardinera",
    "name": "Jardinera",
    "slug": "jardinera",
    "description": "Producto congelado para negocios, cocinerias y locales de comida. Confirmar disponibilidad directamente con Hugo.",
    "category": "Papas y vegetales",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$500",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/jardinera.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "mango-en-trozos",
    "name": "Mango En Trozos",
    "slug": "mango-en-trozos",
    "description": "Producto congelado disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Congelados",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$5.400",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/mango-en-trozos.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "melon-tuna",
    "name": "Melon Tuna",
    "slug": "melon-tuna",
    "description": "Producto congelado disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Congelados",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$3.200",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/melon-tuna.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "mix-frutos-rojos",
    "name": "Mix Frutos Rojos",
    "slug": "mix-frutos-rojos",
    "description": "Producto congelado disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Congelados",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$4.700",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/mix-frutos-rojos.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "mix-tropical-1",
    "name": "Mix Tropical 1",
    "slug": "mix-tropical-1",
    "description": "Producto congelado disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Congelados",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$4.300",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/mix-tropical-1.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "nuggets-pollo",
    "name": "Nuggets Pollo",
    "slug": "nuggets-pollo",
    "description": "Producto disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Pollos",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$2.100",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/nuggets-pollo.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "papas-fritas",
    "name": "Papas Fritas",
    "slug": "papas-fritas",
    "description": "Producto congelado para negocios, cocinerias y locales de comida. Confirmar disponibilidad directamente con Hugo.",
    "category": "Papas y vegetales",
    "format": "Bolsa 2.5 kilos",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$4.300",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/papas-fritas.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "pina",
    "name": "Pina",
    "slug": "pina",
    "description": "Producto congelado disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Congelados",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$5.500",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/pina.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "pizza",
    "name": "Pizza",
    "slug": "pizza",
    "description": "Producto disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Otros",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$3.800",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/pizza.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "pulpa-de-frambuesa",
    "name": "Pulpa De Frambuesa",
    "slug": "pulpa-de-frambuesa",
    "description": "Producto congelado disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Congelados",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$5.300",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/pulpa-de-frambuesa.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "pulpa-de-frutilla-con-azucar",
    "name": "Pulpa De Frutilla Con Azucar",
    "slug": "pulpa-de-frutilla-con-azucar",
    "description": "Producto congelado disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Congelados",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$3.000",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/pulpa-de-frutilla-con-azucar.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "pulpa-de-mango-con-azucar",
    "name": "Pulpa De Mango Con Azucar",
    "slug": "pulpa-de-mango-con-azucar",
    "description": "Producto congelado disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Congelados",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$4.100",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/pulpa-de-mango-con-azucar.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "pulpa-de-pina",
    "name": "Pulpa De Pina",
    "slug": "pulpa-de-pina",
    "description": "Producto congelado disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Congelados",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$3.900",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/pulpa-de-pina.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "pulpa-de-maracuya-sin-azucar",
    "name": "Pulpa De Maracuya Sin Azucar",
    "slug": "pulpa-de-maracuya-sin-azucar",
    "description": "Producto congelado disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Congelados",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$7.000",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/pulpa-de-maracuya-sin-azucar.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "sofrito",
    "name": "Sofrito",
    "slug": "sofrito",
    "description": "Producto congelado para negocios, cocinerias y locales de comida. Confirmar disponibilidad directamente con Hugo.",
    "category": "Papas y vegetales",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$600",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/sofrito.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  },
  {
    "id": "trutos-de-pollo",
    "name": "Trutos De Pollo",
    "slug": "trutos-de-pollo",
    "description": "Producto disponible para solicitud comercial. Confirmar disponibilidad directamente con Hugo.",
    "category": "Pollos",
    "format": "Consultar presentacion",
    "conservation": "Congelado",
    "code": "Consultar codigo",
    "price": "$3.700",
    "observation": "Ideal para restaurantes, minimarkets o distribuidores.",
    "imageUrl": "/images/productos/trutos-de-pollo.png",
    "status": "available",
    "isActive": true,
    "featured": false,
    "createdAt": "2026-05-21T02:53:19.301Z",
    "updatedAt": "2026-05-21T02:53:19.301Z"
  }
];
