import type { Category, Customer, Order } from "./types";
import { generatedProducts } from "./generated-products";

export const products = generatedProducts;

export const categories: Category[] = [
  { id: "cat-pollos", name: "Pollos", slug: "pollos" },
  { id: "cat-cerdo", name: "Cerdo", slug: "cerdo" },
  { id: "cat-vacuno", name: "Vacuno", slug: "vacuno" },
  { id: "cat-cecinas", name: "Cecinas", slug: "cecinas" },
  { id: "cat-congelados", name: "Congelados", slug: "congelados" },
  { id: "cat-papas-vegetales", name: "Papas y vegetales", slug: "papas-y-vegetales" },
  { id: "cat-otros", name: "Otros", slug: "otros" },
];

export const customers: Customer[] = [
  {
    id: "cli-1",
    businessName: "Minimarket Santa Rosa",
    contactName: "Carolina Perez",
    rut: "76.111.222-3",
    phone: "+56981234567",
    commune: "Rancagua",
    address: "Av. Principal 123",
    createdAt: "2026-05-18T10:30:00.000Z",
  },
  {
    id: "cli-2",
    businessName: "Cocineria El Buen Sabor",
    contactName: "Miguel Rojas",
    phone: "+56982345678",
    commune: "Machali",
    address: "Camino Interior 456",
    createdAt: "2026-05-19T14:20:00.000Z",
  },
  {
    id: "cli-3",
    businessName: "Almacen Los Aromos",
    contactName: "Daniela Soto",
    phone: "+56983456789",
    commune: "Graneros",
    address: "Los Aromos 789",
    createdAt: "2026-05-20T09:10:00.000Z",
  },
];

export const orders: Order[] = [
  {
    id: "ord-1",
    code: "PED-2026-00001",
    customer: customers[0],
    status: "pending",
    desiredDate: "2026-05-21",
    desiredTimeRange: "Mañana",
    comment: "Consultar entrega durante la mañana.",
    createdAt: "2026-05-20T11:00:00.000Z",
    updatedAt: "2026-05-20T11:00:00.000Z",
    items: [
      {
        id: "it-1",
        productId: "alitas",
        productName: "Alitas",
        quantity: 2,
        format: "Consultar presentacion",
        conservation: "Congelado",
        code: "Consultar codigo",
        price: "Consultar",
        observation: "Ideal para restaurantes, minimarkets o distribuidores.",
      },
      {
        id: "it-2",
        productId: "papa-frita",
        productName: "Papa Frita",
        quantity: 4,
        format: "Consultar presentacion",
        conservation: "Congelado",
        code: "Consultar codigo",
        price: "Consultar",
        observation: "Producto recomendado para venta por volumen.",
      },
    ],
  },
  {
    id: "ord-2",
    code: "PED-2026-00002",
    customer: customers[1],
    status: "confirmed",
    desiredDate: "2026-05-22",
    desiredTimeRange: "Tarde",
    comment: "Cliente pide confirmar stock antes de despacho.",
    createdAt: "2026-05-19T15:00:00.000Z",
    updatedAt: "2026-05-19T16:00:00.000Z",
    items: [
      {
        id: "it-3",
        productId: "hamburguesa",
        productName: "Hamburguesa",
        quantity: 3,
        format: "Consultar presentacion",
        conservation: "Congelado",
        code: "Consultar codigo",
        price: "Consultar",
        observation: "Ideal para negocios, cocinerias y locales de comida.",
      },
      {
        id: "it-4",
        productId: "choclo",
        productName: "Choclo",
        quantity: 2,
        format: "Consultar presentacion",
        conservation: "Congelado",
        code: "Consultar codigo",
        price: "Consultar",
        observation: "Producto sujeto a disponibilidad.",
      },
    ],
  },
  {
    id: "ord-3",
    code: "PED-2026-00003",
    customer: customers[2],
    status: "delivered",
    desiredDate: "2026-05-24",
    desiredTimeRange: "Indiferente",
    comment: "Entregar junto con pedido semanal.",
    createdAt: "2026-05-18T12:00:00.000Z",
    updatedAt: "2026-05-18T18:00:00.000Z",
    items: [
      {
        id: "it-5",
        productId: "nuggets",
        productName: "Nuggets",
        quantity: 5,
        format: "Consultar presentacion",
        conservation: "Congelado",
        code: "Consultar codigo",
        price: "Consultar",
        observation: "Ideal para negocios, cocinerias y locales de comida.",
      },
      {
        id: "it-6",
        productId: "mix-tropical",
        productName: "Mix Tropical",
        quantity: 2,
        format: "Consultar presentacion",
        conservation: "Congelado",
        code: "Consultar codigo",
        price: "Consultar",
        observation: "Consultar disponibilidad directamente con Hugo.",
      },
    ],
  },
];
